### ISSUE TITLE
rlottie missing

### ISSUE THREAD

**Issue by jlslinux** [batden/emeritux#1] opened 2019-07-09 06:49 UTC
Hi 
Your script is giving error on rlottie missing, so I had to install form 
https://github.com/Samsung/rlottie

**Comment by batden** [comment] 2019-07-09 17:00
Hi,
Thanks for your report!
Please make sure you're using the latest verstion of the script.
The rlottie library is not a hard requirement.
The error was caused by an incorrect flag: '-Devas-loaders-disabler='
added to the build_optim, rebuild_optim and rebuild_wld functions.
This should be fixed unless you are running an old version.

**Closed** 2019-07-13 04:54 UTC
